apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment-service1-frontend-caller.yaml
  - deployment-service2-backend-target.yaml
  - service-service1-frontend.yaml
  - service-service2-backend.yaml
  - destinationrule-circuit-breaker.yaml
  - httproute-circuit-breaker-frontend.yaml
  - authpolicy-circuit-breaker-jwt.yaml
  - rolebinding-circuit-breaker-image-pull-cross-namespace.yaml
