apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - circuit-breaker-destinationrule.yaml
  - circuit-breaker-service-httproute.yaml
  - circuit-breaker-service-authpolicy.yaml
