apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service1-frontend-deployment.yaml
  - service2-backend-deployment.yaml
  - service1-frontend-service.yaml
  - service2-backend-service.yaml
  - circuit-breaker-destinationrule.yaml
  - circuit-breaker-service-httproute.yaml
  - circuit-breaker-service-authpolicy.yaml
