# Definiciones de los pipelines (CI y CD separados) y la identidad que los ejecuta.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - builder-serviceaccount.yaml
  - builder-rolebinding.yaml
  - builder-scc-rolebinding.yaml
  - ci-build-image-pipeline.yaml
  - cd-deploy-application-pipeline.yaml
