# Definiciones de los pipelines (CI y CD separados) y la identidad que los ejecuta.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - constructor-serviceaccount.yaml
  - constructor-rolebinding.yaml
  - constructor-scc-rolebinding.yaml
  - ci-construir-imagen-pipeline.yaml
  - cd-desplegar-aplicacion-pipeline.yaml
