# Configuración del propio Argo CD: proyectos que acotan qué puede desplegarse.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
  - argocd-openshift-gitops-tuning.yaml
  - workshop-platform-appproject.yaml
  - clusterrole-argocd-gateway-api.yaml
