# En dev el issuer apunta al Keycloak del cluster de desarrollo.
apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: canary-service
spec:
  rules:
    authentication:
      token-valido:
        jwt:
          issuerUrl: https://sso.apps.cluster-pvsbw.dyn.redhatworkshops.io/realms/workshop
