# En dev el issuer apunta al Keycloak del cluster de desarrollo.
apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: api-service
spec:
  rules:
    authentication:
      token-valido:
        jwt:
          # Sustituir por el issuer del Keycloak del cluster de DESARROLLO: https://sso.apps.<cluster-dev>.<dominio-base>/realms/workshop
          issuerUrl: https://sso.apps.cluster-dev.ejemplo.com/realms/workshop
