apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: circuit-breaker-service
spec:
  rules:
    authentication:
      token-valido:
        jwt:
          issuerUrl: https://sso.apps.cluster-pvsbw.dyn.redhatworkshops.io/realms/workshop
