apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: bluegreen-service
spec:
  rules:
    authentication:
      token-valido:
        jwt:
          # Sustituir por el host de Keycloak del cluster de DESARROLLO.
          issuerUrl: https://sso.apps.cluster-qthlq.dyn.redhatworkshops.io/realms/workshop
