apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: bluegreen-service
spec:
  hostnames:
    # Sustituir por el dominio del cluster de DESARROLLO: apps.<cluster-dev>.<dominio-base>
    - bluegreen-dev.apps.cluster-dev.ejemplo.com
