apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bluegreen-service-blue-deployment.yaml
  - bluegreen-service-green-deployment.yaml
  - bluegreen-service-blue-service.yaml
  - bluegreen-service-green-service.yaml
  - bluegreen-service-httproute.yaml
  - bluegreen-service-authpolicy.yaml
