apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment-bluegreen-blue-active.yaml
  - deployment-bluegreen-green-standby.yaml
  - service-bluegreen-blue.yaml
  - service-bluegreen-green.yaml
  - httproute-bluegreen-traffic-switch.yaml
  - authpolicy-bluegreen-jwt.yaml
