apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - canary-service-v1-deployment.yaml
  - canary-service-v2-deployment.yaml
  - canary-service-v1-service.yaml
  - canary-service-v2-service.yaml
  - canary-service-httproute.yaml
  - canary-service-authpolicy.yaml
