apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment-canary-v1-stable.yaml
  - deployment-canary-v2-candidate.yaml
  - service-canary-v1.yaml
  - service-canary-v2.yaml
  - httproute-canary-weighted-split.yaml
  - authpolicy-canary-jwt.yaml
  - rolebinding-canary-image-pull-cross-namespace.yaml
